import { ComponentData } from "./types";

export const components: ComponentData[] = [
  {
    id: "Launch-Button",
    name: "Launch Button",
    shortDescription: "Sleek button with fluid square arrow animation.",
    longDescription: "A high-fidelity interactive button designed with Framer Motion. Features a unique grid-based arrow animation that activates on hover. Fully customizable props for colors, speed, and labels make it perfect for any landing page launch action.",
    video: "https://pub-ce7c82a074d24c96a153a74a9158dc02.r2.dev/blocks_demo/launch_button.mp4",
    type: "components",
    subsection: "button",
    category: "button",
    date: "2026-04-11",
    tags: ["Framer Motion", "Button", "Micro-interaction", "Next.js"],
    block_url: "https://t7blocks.xyz/components/button/launch-button",
    canvas: {
      background: "#EBEBEB",
      height: "100vh",
    }
  },
  {
    id: "Pop-Hero",
    name: "Pop Hero",
    shortDescription: "Cinematic hero with fluid GSAP pop-up animation.",
    longDescription: "A GSAP-powered hero section featuring fluid pop-up transitions, fullscreen video background, and immersive typography. Designed for modern landing pages, it delivers smooth animations, premium visuals, and high-impact user engagement.",
    video: "https://pub-ce7c82a074d24c96a153a74a9158dc02.r2.dev/blocks_demo/pop_hero.mp4",
    type: "sections",
    subsection: "hero",
    category: "hero",
    date: "2026-04-11",
    tags: ["GSAP", "Hero", "Animation", "Next.js"],
    block_url: "https://t7blocks.xyz/sections/hero/pop-hero",
    canvas: {
      background: "#000000",
      height: "100vh",
    }
  },
  {
    id: "Scroll-Image-Pass",
    name: "Scroll Image Pass",
    shortDescription: "Staggered vertical image scroll with GSAP transition",
    longDescription: "GSAP-powered pinned scroll section with staggered vertical image passes, dynamic title scaling, and a final image-driven layout transition.",
    video: "https://pub-ce7c82a074d24c96a153a74a9158dc02.r2.dev/blocks_demo/scroll-image-pass.mp4",
    type: "interactions",
    subsection: "scroll",
    category: "scroll",
    date: "2026-04-11",
    tags: ["GSAP", "Scroll", "Animation", "Gallery", "Image"],
    block_url: "https://t7blocks.xyz/interactions/scroll/scroll-image-pass",
    canvas: {
      background: "#FFFFFF",
      height: "100vh",
      width: "100vw",
      className: "!block !p-0 !m-0 "
    }
  },
  {
    id: "Sticky-Scroll",
    name: "Sticky Scroll",
    shortDescription: "Staggered vertical image scroll with GSAP transition",
    longDescription: "GSAP-powered pinned scroll section with staggered vertical image passes, dynamic title scaling, and a final image-driven layout transition.",
    video: "https://pub-4b0a8f18a97e4b44914872dd0d22870b.r2.dev/blog_demo/scroll_trigger_demo_compress.mp4",
    type: "interactions",
    subsection: "scroll",
    category: "scroll",
    date: "2026-04-11",
    tags: ["GSAP", "Scroll", "Animation", "Gallery", "Image"],
    block_url: "https://t7blocks.xyz/interactions/scroll/sticky-scroll",
    canvas: {
      background: "#FFFFFF"
    }
  },
  {
    id: "pull-switch",
    name: "Pull Switch",
    shortDescription: "Interactive pull-cord switch to toggle light and dark mode",
    longDescription: "A canvas-based pull-cord switch component with physics-driven rope interaction. Users can drag and pull the cord to toggle between light and dark themes, with smooth motion, realistic constraints, and animated color transitions.",
    video: "https://pub-ce7c82a074d24c96a153a74a9158dc02.r2.dev/blocks_demo/pullswitch.mp4",
    type: "misc",
    noSubsection: true,
    category: "misc",
    date: "2026-04-11",
    tags: ["Canvas", "Animation", "button", "Theme", "Dark Mode", "Interaction"],
    block_url: "https://t7blocks.xyz/misc/pull-switch",
    canvas: {
      background: "transparent",
      height: "100vh",
      width: "100vw",
      className: "!block !p-0 !m-0 !overflow-hidden",
    }
  },
  {
    id: "knob-toggle",
    name: "Knob Toggle",
    shortDescription: "A knob toggle to switch between light and dark mode",
    longDescription: "A premium knob toggle component with smooth sliding, sound effects, and instant theme switching. Perfect for adding a tactile, high-quality interaction to your website.",
    video: "https://pub-ce7c82a074d24c96a153a74a9158dc02.r2.dev/blocks_demo/KnobButton.mp4",
    type: "components",
    subsection: "button",
    category: "button",
    date: "2026-04-11",
    tags: ["Button", "Animation", "Theme", "Dark Mode", "Interaction", "sound"],
    block_url: "https://t7blocks.xyz/components/button/knob-toggle",
    canvas: {
      background: "transparent",
      height: "100vh",
      width: "100vw",
      className: "!block !p-0 !m-0 !overflow-hidden",
    }
  }, {
    id: "wave-button",
    name: "Wave Button",
    shortDescription: "A button with a wave animation",
    longDescription: "A button with a wave animation that is triggered on hover",
    video: "https://pub-ce7c82a074d24c96a153a74a9158dc02.r2.dev/blocks_demo/wavebutton.mp4",
    type: "components",
    subsection: "button",
    category: "button",
    date: "2026-04-11",
    tags: ["Button", "Interaction", "Wave", "Framer Motion"],
    block_url: "https://t7blocks.xyz/components/button/wave-button",
    canvas: {
      background: "#FFFFFF",
      height: "100vh",
      width: "100vw",
      className: "flex items-center justify-center",
    },
  }, {
    id: "bouncy-button",
    name: "Bouncy Button",
    shortDescription: "A button with a bouncy animation",
    longDescription: "A button with a bouncy animation that is triggered on hover",
    video: "https://pub-ce7c82a074d24c96a153a74a9158dc02.r2.dev/blocks_demo/bouncybutton.mp4",
    type: "components",
    subsection: "button",
    category: "button",
    date: "2026-04-11",
    tags: ["Button", "Interaction", "Bouncy", "Framer Motion"],
    block_url: "https://t7blocks.xyz/components/button/bouncy-button",
    canvas: {
      background: "https://pub-30f77b34698b4af9acb780d4dfe7ee4d.r2.dev/good_bg/Moon2011%20(1).png",
      height: "100vh",
      width: "100vw",
      className: "flex items-center justify-center",
    },
  }, {
    id: "stagger-text",
    name: "Stagger Text",
    shortDescription: "A text with a stagger animation on hover",
    longDescription: "A text with a stagger animation that is triggered on hover",
    video: "https://pub-ce7c82a074d24c96a153a74a9158dc02.r2.dev/blocks_demo/staggertext.mp4",
    type: "components",
    subsection: "text",
    category: "text",
    date: "2026-04-11",
    tags: ["Text", "Animation", "Hover", "Interactive", "Typography"],
    block_url: "https://t7blocks.xyz/components/text/staggertext",
    canvas: {
      background: "https://pub-30f77b34698b4af9acb780d4dfe7ee4d.r2.dev/good_bg/blue_orange.png",
      height: "100vh",
      width: "100vw",
      className: "flex items-center justify-center",
    },
  },{
    id: "falling-text",
    name: "Falling Text",
    shortDescription: "A text with a falling animation",
    longDescription: "A text with a falling animation that is triggered on scroll",
    video: "https://pub-ce7c82a074d24c96a153a74a9158dc02.r2.dev/blocks_demo/fallingtext.mp4",
    type: "components",
    subsection: "text",
    category: "text",
    date: "2026-04-11",
    tags: ["Text", "Animation", "Hover", "Interactive", "Typography"],
    block_url: "https://t7blocks.xyz/components/text/fallingtext",
    canvas: {
      background: "https://pub-30f77b34698b4af9acb780d4dfe7ee4d.r2.dev/good_bg/bg_blue.png",
    },
  },{
    id: "lottietext",
    name: "Lottie Text",
    shortDescription: "A a lottie animation embedded in the text",
    longDescription: "This text block combines plain text with lottie animations that seamlessly integrate into words.",
    video: "https://pub-ce7c82a074d24c96a153a74a9158dc02.r2.dev/blocks_demo/lottietext.mp4",
    type: "components",
    subsection: "text",
    category: "text",
    date: "2026-04-11",
    tags: ["Text", "Animation", "Hover", "Interactive", "Typography"],
    block_url: "https://t7blocks.xyz/components/text/lottietext",
    canvas: {
      background: "https://images.unsplash.com/photo-1724942462164-7c30f103d91c",
       height: "100vh",
      width: "100vw",
      className: "min-h-screen flex items-center justify-center bg-white",
    },
  }
];
